[package]
name = "ammonia-crash-test"
version = "0.1.0"
authors = ["Bauke <me@bauke.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ammonia = "3.1"
